services:
  app:
    build:
      context: .
      dockerfile: .docker/app/Dockerfile
    container_name: app
    working_dir: /var/www
    volumes:
      - ./:/var/www
    depends_on:
      - db
    networks:
      - laravel
    environment:
      APP_ENV: ${APP_ENV}
      APP_DEBUG: ${APP_DEBUG}
      APP_KEY: ${APP_KEY}
      APP_URL: ${APP_URL}

  db:
    image: postgres:15
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - laravel

  nginx:
    image: nginx:alpine
    container_name: nginx_web
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

  swagger:
    image: swaggerapi/swagger-ui
    container_name: swagger_ui
    ports:
      - "${SWAGGER_PORT}:8080"
    environment:
      SWAGGER_JSON: /api-docs/openapi.json
    volumes:
      - ./storage/api-docs:/api-docs
    networks:
      - laravel

volumes:
  postgres_data:

networks:
  laravel:
    driver: bridge
